### ISSUE TITLE
make target bin-x86_64-efi/ipxe.usb fails with Error: operand size mismatch for `push'

### ISSUE THREAD

**Issue by jstncno** [ipxe/ipxe#997]
Hello,

I have been building ipxe from source using `make bin-x86_64-efi/ipxe.usb`. Lately I've been receiving the following errors:

```
$ make bin-x86_64-efi/ipxe.usb
  ...
  [BUILD] bin-x86_64-efi/bootsector.o
arch/x86/image/bootsector.c: Assembler messages:
arch/x86/image/bootsector.c:85: Error: operand size mismatch for `push'
make: *** [Makefile.housekeeping:964: bin-x86_64-efi/bootsector.o] Error 1
```

Could anybody help me troubleshoot this issue? Thanks

**Comment by NiKiZe** [comment]
If this has worked previously, please use instructions at https://ipxe.org/howto/bisect to identify commits introducing issues.
Also make sure you don't have any local modifications.

If you can't find a working commit at all, please make sure to include versions of your toolchain, especially gcc.

boot.ipxe.org produces builds every hour, so there shouldn't be anything that could break for everyone being commited to the tree.

**Comment by jstncno** [comment]
Thanks @NiKiZe for the quick response. It seems it has to do with my toolchain as I was able to successfully build in a vanilla Ubuntu environment.

My working env has gcc v10.2.1 while the non-working env has gcc v10.4.0. Is there a way to check for the correct toolchain?

**Comment by mcb30** [comment]
This looks like a gcc bug.  There are precisely three `push` instructions within that inline assembly (including the implicit `push $1f` created by the `REAL_CODE()` macro), and none of them are problematic.

From your description of this as being fixed by using a "vanilla Ubuntu environment", I'm guessing that you may have a locally built `gcc` in your original environment, in which case that is most likely to be the source of the problem.

Closing: please reopen if you are able to reproduce the error in some kind of "standard" environment.

**Comment by jstncno** [comment]
@mcb30 thanks for your response.

With some help from some colleagues, we were able to determine the root cause.

It seems that this is likely a change in the `binutils` package (specifically the assembler, `as`) rather than `gcc`.

In my working environment (I mistakenly mentioned "vanilla Ubuntu" instead of "vanilla Debian"), running `as --version` shows version `2.35.2`:
```
GNU assembler (GNU Binutils for Debian) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
```

In my non-standard, non-working environment, `as --version` shows version `2.40.50.20230611`:
```
GNU assembler (GNU Binutils for Debian) 2.40.50.20230611
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
```

It makes to keep this ticket closed since this is still a "non-standard" environment, but wanted to post this info if this issue ever propagates.

Thanks again!

**Comment by sonic42** [comment]
Hi
The problem persists with new released binutils package 2.41 https://www.gnu.org/software/binutils/
 as --version
GNU assembler (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-pc-linux-gnu'``

**Comment by NiKiZe** [comment]
Is this on one machine or multiple?
What is needed to reproduce so we can create a VM and test?

**Comment by sonic42** [comment]
After to upgrading a LFS based distri toolchain with fresh released binutils  2.41 / gcc 13.2 and glibc 2.38, some packages fails build. I'm using a Debian based VM for development. This are the first tests with this new  binutils, gcc and glibc releases. After some testing use of previous versions of gcc and glibc to compile ipxe , the error raises the new binutils package.  The error is currently on one machine. Tests in a second manjaro / arch based build environment will follow...

**Comment by sonic42** [comment]
The build are successful.  Thanks.

**Comment by jstncno** [comment]
Can this issue be reopened, since this reproducible with `as` v2.40+ ?

**Comment by NiKiZe** [comment]
Is there any bug or documentation in/from vinutils on this?

**Comment by ipaqmaster** [comment]
That patch resolved it for me. Thanks @jstncno

**Comment by mcb30** [comment]
I am unable to reproduce the issue.  I get a successful build using binutils 2.41:
```console
$ as --version
GNU assembler version 2.41-5.fc40
```

I'm happy to look into this further, but only if someone can provide me with a simple way to reproduce the problem.

**Comment by c---** [comment]
Building using Arch Linux I get the error:
```
$ git clone https://git.ipxe.org/ipxe.git
$ cd ipxe/src
$ make bin-x86_64-efi/ipxe.efi

  [BUILD] bin-x86_64-efi/bootsector.o
arch/x86/image/bootsector.c: Assembler messages:
arch/x86/image/bootsector.c:85: Error: operand size mismatch for `push'
make: *** [Makefile.housekeeping:964: bin-x86_64-efi/bootsector.o] Error 1
```

```
$ as --version
GNU assembler (GNU Binutils) 2.41.0
```

**Comment by mcb30** [comment]
OK, I have reproduced the problem.  My fault for using a plain `make` to test, which doesn't exercise the 64-bit build path.  :man_facepalming: 

I have a simplified test case, independent of iPXE:
```shell
as -o /dev/null <<'EOF'
    .text
    push $1f
1:
EOF
```

I have bisected this down to binutils commit https://github.com/bminor/binutils-gdb/commit/5cc007751cdb8ea713c98294e37cd447c12c9bab ("x86: further adjust extend-to-32bit-address conditions").  I don't fully understand what's going on in that commit, but it definitely does relate to operand sizes.  That commit first appeared in binutils-2.41, which matches the issue reports.
